version: '3.8'

services:
  event-feed-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - .:/app:rw
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
    # Override healthcheck for development
    healthcheck:
      interval: 60s
